all:
  hosts:
    rke-main-01-p:
      ansible_host: 10.10.13.10
    rke-main-02-p:
      ansible_host: 10.10.13.11
    rke-main-03-p:
      ansible_host: 10.10.13.12
    rke-work-01-p:
      ansible_host: 10.10.13.13
    rke-work-02-p:
      ansible_host: 10.10.13.14
    rke-work-03-p:
      ansible_host: 10.10.13.15
    rke-work-04-p:
      ansible_host: 10.10.13.16
    rke-work-05-p:
      ansible_host: 10.10.13.17
    rke-svc-01-p:
      ansible_host: 10.10.13.18
    rke-svc-02-p:
      ansible_host: 10.10.13.19
    rke-svc-03-p:
      ansible_host: 10.10.13.20

  children:
    masters:
      hosts:
        rke-main-01-p:
        rke-main-02-p:
        rke-main-03-p:

    workers:
      hosts:
        rke-work-01-p:
        rke-work-02-p:
        rke-work-03-p:
        rke-work-04-p:
        rke-work-05-p:
        rke-svc-01-p:
          k8s_node_label:
            - "app=nginx-ingress"
            - "metrics=prometheus"
        rke-svc-02-p:
          k8s_node_label:
            - "app=nginx-ingress"
            - "metrics=prometheus"
        rke-svc-03-p:
          k8s_node_label:
            - "app=nginx-ingress"
            - "metrics=prometheus"
      vars:
        k8s_node_label:
          - "vsphere-csi-node=true"

    k8s_cluster:
      children:
        masters: {}
        workers: {}
