all:
  hosts:
    lb1:
      ansible_host: 192.168.100.110
    lb2:
      ansible_host: 192.168.100.111

  children:
    app:
      hosts:
        lb1:
        lb2:

  vars:
    enable_ssl: true
    keepalived_install: true
    keepalived_virtual_ip: 192.168.100.100
    ansible_ssh_private_key_file: ~/.ssh/ansible_home.local

    ################################################################
    # Frontends configuration
    ################################################################
    haproxy_frontends:
      - name: "https_haproxy"
        mode: http
        bind_address: "192.168.100.100"
        bind_ports:
          - port: "443"
            bind_options: "ssl crt /etc/haproxy/ssl/wildcard_home.local.pem"
        used_backend: true
        use_backend:
          - backend_name: "secret_web"
            rule: "if { src 10.0.0.0/8 } { hdr(host) -i secret.home.local }"
          - backend_name: "www_home"
            rule: "if { hdr(host) -i www.home.local }"
          - backend_name: "metrics-test"
            rule: "if { hdr_reg(host) -i ^test-.*\\.home\\.local$ } { path_beg /metrics }"
          - backend_name: "www_end_of"
            rule: "if { hdr_end(host) -i .end.home.local }"
          - backend_name: "rancher_web"
            rule: "if { hdr(host) -i rancher.home.local }"

        vars:
          - "option httplog"
          - "option forwardfor"
          - "http-request set-header X-Forwarded-Proto https"
          - "acl hdr_connection_upgrade hdr(Connection) -i upgrade"
          - "acl is_websocket hdr(Upgrade) -i websocket"
          - "http-request set-header Connection 'upgrade' if hdr_connection_upgrade is_websocket"
          - "http-request set-header Upgrade 'websocket' if hdr_connection_upgrade is_websocket"

      - name: "stats"
        mode: "http"
        bind_address: "192.168.100.100"
        bind_ports:
          - port: "8888"
        vars:
          - "stats enable"
          - "stats uri /stats"
          - "stats refresh 15s"
          - "stats auth admin:admin"

      ##############################################################
      # Kubernetes Agents
      ##############################################################
      - name: "k8s_workload_agent_api"
        mode: tcp
        bind_address: "192.168.100.100"
        bind_ports:
          - port: 9345
            bind_options: "name k8s_workload_agent_api"
        vars:
          - "log global"
          - "option tcplog"
          - "option logasap"
          - "option clitcpka"
          - "timeout client 3h"
          - "acl rancher_ips src 192.168.100.152 192.168.100.153 192.168.100.154"
          - "use_backend k8s_rancher_agent_api if rancher_ips"
        backend_name: "k8s_workload_agent_api"

      ##############################################################
      # Kubernetes API
      ##############################################################
      - name: "k8s_kube_workload_api"
        mode: tcp
        bind_address: "192.168.100.100"
        bind_ports:
          - port: 6443
            bind_options: "name k8s_kube_workload_api"
        vars:
          - "log global"
          - "option tcplog"
          - "option logasap"
          - "option clitcpka"
          - "timeout client 3h"
        backend_name: "k8s_kube_workload_api"

      - name: "k8s_kube_rancher_api"
        mode: tcp
        bind_address: "192.168.100.100"
        bind_ports:
          - port: 6444
            bind_options: "name k8s_kube_rancher_api"
        vars:
          - "log global"
          - "option tcplog"
          - "option logasap"
          - "option clitcpka"
          - "timeout client 3h"
        backend_name: "k8s_kube_rancher_api"

    ################################################################
    # Backends configuration
    ################################################################
    haproxy_backends:
      - name: "k8s_workload_agent_api"
        mode: tcp
        balance: "roundrobin"
        servers:
          - name: "rke-master-01"
            address: rke-master-01
            port: 9345
            params:
              - "check inter 2s fall 3"
          - name: "rke-master-02"
            address: rke-master-02
            port: 9345
            params:
              - "check inter 2s fall 3"
          - name: "rke-master-03"
            address: rke-master-03
            port: 9345
            params:
              - "check inter 2s fall 3"
        vars:
          - timeout server 3h

      - name: "k8s_rancher_agent_api"
        mode: tcp
        balance: "roundrobin"
        servers:
          - name: "rke-ranch-01"
            address: rke-ranch-01
            port: 9345
            params:
              - "check inter 2s fall 3"
          - name: "rke-ranch-02"
            address: rke-ranch-02
            port: 9345
            params:
              - "check inter 2s fall 3"
          - name: "rke-ranch-03"
            address: rke-ranch-03
            port: 9345
            params:
              - "check inter 2s fall 3"
        vars:
          - timeout server 3h

      - name: "k8s_kube_workload_api"
        mode: tcp
        balance: "roundrobin"
        servers:
          - name: "rke-master-01"
            address: rke-master-01
            port: 6443
            params:
              - "check inter 2s fall 3"
          - name: "rke-master-02"
            address: rke-master-02
            port: 6443
            params:
              - "check inter 2s fall 3"
          - name: "rke-master-03"
            address: rke-master-03
            port: 6443
            params:
              - "check inter 2s fall 3"
        vars:
          - timeout server 3h

      - name: "k8s_kube_rancher_api"
        mode: tcp
        balance: "roundrobin"
        servers:
          - name: "rke-ranch-01"
            address: rke-ranch-01
            port: 6443
            params:
              - "check inter 2s fall 3"
          - name: "rke-ranch-02"
            address: rke-ranch-02
            port: 6443
            params:
              - "check inter 2s fall 3"
          - name: "rke-ranch-03"
            address: rke-ranch-03
            port: 6443
            params:
              - "check inter 2s fall 3"
        vars:
          - timeout server 3h

      - name: "rancher_web"
        mode: "http"
        servers:
          - name: "rke-ranch-01"
            address: rke-ranch-01
            port: 443
            params:
              - "check ssl verify none weight 1 maxconn 1024"
          - name: "rke-ranch-02"
            address: rke-ranch-02
            port: 443
            params:
              - "check ssl verify none weight 1 maxconn 1024"
          - name: "rke-ranch-03"
            address: rke-ranch-03
            port: 443
            params:
              - "check ssl verify none weight 1 maxconn 1024"

      - name: "www_home"
        mode: "http"
        servers:
          - name: "nginx-01"
            address: 192.168.100.151
            port: 8080
            params:
              - "check weight 1 maxconn 1024"

      - name: "metrics-test"
        mode: "http"
        servers:
          - name: "nginx-01"
            address: 192.168.100.151
            port: 8081
            params:
              - "check weight 1 maxconn 1024"

      - name: "www_end_of"
        mode: "http"
        servers:
          - name: "nginx-01"
            address: 192.168.100.151
            port: 8082
            params:
              - "check weight 1 maxconn 1024"

      - name: "secret_web"
        mode: "http"
        servers:
          - name: "nginx-01"
            address: 192.168.100.151
            port: 8083
            params:
              - "check weight 1 maxconn 1024"
